name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: minvs1
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build image
      run: docker build . --file Dockerfile --tag minvs1/airnote:${GITHUB_SHA::8}
    - name: Push image
      run: docker push minvs1/airnote:${GITHUB_SHA::8}
