name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build . --file Dockerfile --tag minvs1/airnote:latest
    - name: Push image
      run: |
        docker login docker.pkg.github.com --username minvs1
        docker tag minvs1/airnote:latest docker.pkg.github.com/minvs1/airnote/airnote:$GITHUB_SHA
        docker push docker.pkg.github.com/minvs1/airnote/airnote:$GITHUB_SHA
